#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
logo_darkmode = "images/logo.png"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "180px"
# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "DataFortress.cloud"
# theme-mode
theme_switcher = true
theme_default = "system" # available options [light/dark/system]
# site-wide feature toggles (default enabled)
enable_animations = true
enable_particles = true
enable_hero3d = true
# Main Sections
mainSections = ["blog"]
# contact form action
contact_form_action = "https://formspree.io/mknvkdpr" # contact form works with [https://airform.io/] or [https://formspree.io]
# demo form action
demo_form_action = "https://formspree.io/mknvkdpr" # demo form works with [https://airform.io/] or [https://formspree.io]
# career form action
career_form_action = "https://formspree.io/mknvkdpr"
# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "GTM-5G9F7KK" # example: G-XXXXXXXXXX
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script = ""
# copyright
theme_copyright = true
copyright = "Copyright by DataFortress.cloud GmbH"

# preloader
# preloader module: https://github.com/gethugothemes/hugo-modules/tree/master/components/preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format. example - "images/preloader.gif"

# Navigation button
[navigation_button]
enable = true
label = "Contact"
link = "contact/"

# crisp chat
# crisp chat module: https://github.com/gethugothemes/hugo-modules/tree/master/components/crisp-chat
[crisp_chat]
enable = true
crisp_website_id = "4453c713-998c-44d9-8968-96ad05471989" # replace this code with yours
# Check this video tutorial to get your crisp website ID - https://www.youtube.com/watch?v=nW5UX6iVdFc

# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["Data Engineering", "Data", "Kubernetes", "Hosting in Germany", "Managed Kubernetes", "Jupyter Notebook", "ETL Pipelines"]
description = "DataFortress.cloud (GmbH) specializes in delivering scalable data engineering, cloud infrastructure, and Kubernetes solutions for enterprise customers. We provide customized services, including cloud migration, DevOps integration, Kubernetes orchestration, and secure data pipeline management. With expertise in multi-cloud and hybrid environments, we help businesses optimize performance, ensure security, and achieve cost efficiency. Trusted by enterprises across industries, DataFortress.cloud is your partner in transforming IT infrastructure for the modern cloud era."
author = "DataFortress.cloud"
image = "images/logo.png"                           # this image will be used as fallback if a page has no image of its own

# matomo tracking: see https://matomo.org/
# matomo tracking module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/matomo-analytics
[matomo]
enable = false
url = ""       # your matomo url
id = ""        # your matomo id

# baidu analytics: see https://tongji.baidu.com/
# baidu analytics module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/baidu-analytics
[baidu]
enable = false
analytics_id = "" # Your ID

# plausible analytics: see https://plausible.io/
# plausible analytics module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/plausible-analytics
[plausible]
enable = false
domain = ""    # yourdomain.com

# counter analytics: see https://counter.dev/setup.html
# counter analytics module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/counter-analytics
[counter]
enable = false
username = ""  # your username

# site verifications
# site verifications module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/site-verifications
[site_verification]
google = ""   # Your verification code
bing = ""     # Your verification code
baidu = ""    # Your verification code
facebook = "" # Your verification code
mastodon = "" # Your verification code

# cookies
# cookies module: https://github.com/gethugothemes/hugo-modules/tree/master/components/cookie-consent
[cookies]
enable = false
expire_days = 7
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

############################# social site ########################
[[params.social]]
title = "facebook"
icon = "fab fa-facebook" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.facebook.com/datafortress.cloud"

# [[params.social]]
# title = "twitter"
# icon = "fab fa-twitter" # fontawesome icon pack : https://fontawesome.com/icons/
# link = "#!"

# [[params.social]]
# title = "instagram"
# icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
# link = "#!"

[[params.social]]
title = "github"
icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://github.com/JustinGuese"

[[params.social]]
title = "linkedin"
icon = "fab fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.linkedin.com/company/49084538"
